// tokens/generate.mjs
// Design-token generator for FADA.
// Usage: node tokens/generate.mjs  (run from the app/ directory)
//
// Reads:  tokens/design-tokens.json
// Emits:  styles/tokens.css           — CSS custom properties on :root
//         tailwind.theme.generated.ts  — TS mirror for IDE autocomplete
//
// Run automatically via "predev" / "prebuild" npm scripts.

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

import { TokensSchema } from "./schema.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

// ─── 1. Load + validate ──────────────────────────────────────────────────────

const rawJson = readFileSync(resolve(__dirname, "design-tokens.json"), "utf8");
const parsed = JSON.parse(rawJson);
const result = TokensSchema.safeParse(parsed);

if (!result.success) {
  console.error("❌  design-tokens.json failed schema validation:");
  console.error(result.error.format());
  process.exit(1);
}

const tokens = result.data;

// ─── 2. Flatten helpers ───────────────────────────────────────────────────────

/**
 * Flatten a nested object into CSS variable entries.
 * E.g. { bg: { base: "#0B0D14" } } with prefix "color" →
 *      { "--color-bg-base": "#0B0D14" }
 */
function flattenToCssVars(obj, prefix) {
  const vars = {};
  for (const [key, value] of Object.entries(obj).sort(([a], [b]) =>
    a.localeCompare(b),
  )) {
    const cssKey = `--${prefix}-${key}`;
    if (typeof value === "object" && value !== null) {
      Object.assign(vars, flattenToCssVars(value, `${prefix}-${key}`));
    } else {
      vars[cssKey] = value;
    }
  }
  return vars;
}

// ─── 3. Build CSS variable map ────────────────────────────────────────────────

// Map each top-level token group to a CSS prefix per the naming convention.
const cssVarGroups = [
  flattenToCssVars(tokens.palette.bg, "color-bg"),
  flattenToCssVars(tokens.palette.fg, "color-fg"),
  flattenToCssVars(tokens.palette.accent, "color-accent"),
  { "--color-danger": tokens.palette.danger },
  { "--color-success": tokens.palette.success },
  flattenToCssVars(tokens.type.family, "font"),
  flattenToCssVars(tokens.type.scale, "text"),
  flattenToCssVars(tokens.type.weight, "font-weight"),
  flattenToCssVars(tokens.spacing, "space"),
  flattenToCssVars(tokens.radii, "radius"),
  flattenToCssVars(tokens.motion.duration, "duration"),
  flattenToCssVars(tokens.motion.easing, "ease"),
  flattenToCssVars(tokens.breakpoints, "breakpoint"),
];

// Merge and sort all CSS vars deterministically.
const allCssVars = Object.assign({}, ...cssVarGroups);
const sortedCssVars = Object.fromEntries(
  Object.entries(allCssVars).sort(([a], [b]) => a.localeCompare(b)),
);

// ─── 4. Emit styles/tokens.css ───────────────────────────────────────────────

const cssLines = Object.entries(sortedCssVars).map(
  ([k, v]) => `  ${k}: ${v};`,
);

const cssContent = `/* styles/tokens.css — AUTO-GENERATED by tokens/generate.mjs. DO NOT EDIT. */
/* Source of truth: tokens/design-tokens.json                                  */

:root {
${cssLines.join("\n")}
}
`;

mkdirSync(resolve(ROOT, "styles"), { recursive: true });
writeFileSync(resolve(ROOT, "styles/tokens.css"), cssContent, "utf8");
console.log("✓  styles/tokens.css written");

// ─── 5. Emit tailwind.theme.generated.ts ─────────────────────────────────────
// This file lives at app/tailwind.theme.generated.ts (NOT under tokens/).
// It provides a typed TS mirror of the CSS vars for IDE autocomplete and
// programmatic consumption. Tailwind v4 reads the CSS vars from tokens.css
// (imported via globals.css @import "./tokens.css"); this TS file is for
// TS consumers and tests only.

const tsEntries = Object.entries(sortedCssVars)
  .map(([k, v]) => `  "${k}": "${v}",`)
  .join("\n");

const tsContent = `// tailwind.theme.generated.ts — AUTO-GENERATED by tokens/generate.mjs. DO NOT EDIT.
// Source of truth: tokens/design-tokens.json
//
// This file lives at app/tailwind.theme.generated.ts (not under tokens/) per
// the P1-1 file structure. The @/tokens/* alias does not cover this path —
// import directly: import { theme } from '../tailwind.theme.generated'
//
// Tailwind v4 utility classes are generated from the CSS vars in
// styles/tokens.css (via the @theme inline block in globals.css).
// This TS object provides IDE autocomplete and can be used in tests.

export const theme = {
${tsEntries}
} as const;

export type ThemeKey = keyof typeof theme;
export type ThemeValue = (typeof theme)[ThemeKey];
`;

writeFileSync(resolve(ROOT, "tailwind.theme.generated.ts"), tsContent, "utf8");
console.log("✓  tailwind.theme.generated.ts written");

console.log(
  `\n✓  Generated ${Object.keys(sortedCssVars).length} design tokens`,
);
