// tailwind.theme.generated.ts — AUTO-GENERATED by tokens/generate.mjs. DO NOT EDIT.
// Source of truth: tokens/design-tokens.json
//
// This file lives at app/tailwind.theme.generated.ts (not under tokens/) per
// the P1-1 file structure. The @/tokens/* alias does not cover this path —
// import directly: import { theme } from '../tailwind.theme.generated'
//
// Tailwind v4 utility classes are generated from the CSS vars in
// styles/tokens.css (via the @theme inline block in globals.css).
// This TS object provides IDE autocomplete and can be used in tests.

export const theme = {
  "--breakpoint-lg": "1024px",
  "--breakpoint-md": "768px",
  "--breakpoint-sm": "640px",
  "--breakpoint-wide": "1440px",
  "--breakpoint-xl": "1920px",
  "--color-accent-gold": "#E6B64A",
  "--color-bg-base": "#0B0D14",
  "--color-bg-surface": "#12151F",
  "--color-danger": "#E5484D",
  "--color-fg-muted": "#8A93AB",
  "--color-fg-primary": "#E8ECF5",
  "--color-success": "#2E844A",
  "--duration-fast": "120ms",
  "--duration-normal": "220ms",
  "--duration-slow": "400ms",
  "--ease-default": "cubic-bezier(0.2, 0.8, 0.2, 1)",
  "--font-arabic": "IBM Plex Sans Arabic, sans-serif",
  "--font-mono": "IBM Plex Mono, monospace",
  "--font-weight-bold": "700",
  "--font-weight-medium": "500",
  "--font-weight-normal": "400",
  "--font-weight-semibold": "600",
  "--radius-lg": "12px",
  "--radius-md": "8px",
  "--radius-pill": "9999px",
  "--radius-sm": "4px",
  "--radius-xl": "24px",
  "--space-1": "4px",
  "--space-12": "48px",
  "--space-16": "64px",
  "--space-2": "8px",
  "--space-3": "12px",
  "--space-4": "16px",
  "--space-6": "24px",
  "--space-8": "32px",
  "--text-2xl": "36px",
  "--text-3xl": "48px",
  "--text-base": "16px",
  "--text-lg": "18px",
  "--text-md": "14px",
  "--text-sm": "12px",
  "--text-xl": "22px",
  "--text-xxl": "28px",
} as const;

export type ThemeKey = keyof typeof theme;
export type ThemeValue = (typeof theme)[ThemeKey];
